### PR TITLE
Automatically runs Rubocop on save

### PR DESCRIPTION
**Pull request by dcluna**
Does exactly what it says on the tin.

Addresses https://github.com/rubocop-hq/rubocop-emacs/issues/10, and probably https://github.com/rubocop-hq/rubocop-emacs/issues/21 too.

### CODE REVIEW

**Comment by sadhu89** [comment]
This is great! Could I make it work with `--safe-autocorrect`?

**Comment by sadhu89** [comment]
I have been using these a couple of days and I love it. Is there a way I can avoid it gets executed when `super-save` saves the file automatically?

**Comment by dcluna** [comment]
@sadhu89 I was thinking you could customize [this function](https://github.com/bbatsov/super-save/blob/master/super-save.el#L74) in `super-save`, maybe using one of the `advice`s defined there to temporarily set the `defcustom` defined here to `nil`. WDYT?

**Comment by bbatsov** [comment]
I forgot to merge this. Please rebase it and ping me afterwards, so we can wrap it up.

**Comment by dcluna** [comment]
@bbatsov ping

**Comment by bbatsov** [comment]
Thanks!

**Comment by grauschnabel** [comment]
Could you make a statement in the README.md also?  I always get 
`Compilation exited abnormally with code 127`
but don't know which settings are wrong.

**Comment by dcluna** [comment]
@grauschnabel If you run `rubocop-autocorrect-current-file` interactively, does it work?

I recommend doing `bundle install` after ensuring `rubocop` is in the project's `Gemfile` or setting `rubocop-prefer-system-executable` to `t` if that's what you use.

**Pull request merged**
